language: julia
julia:
  - 1.1
codecov: true
coveralls: true

script:
  - julia -e 'using Pkg; Pkg.instantiate()'
  - julia --code-coverage=user --inline=no 'test/runtests.jl'

after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - julia -e ' Codecov.submit(Codecov.process_folder())'
