language: julia
julia:
  - 1.0
  - 1.1

script:
  - julia --code-coverage=user --inline=no test/runtests.jl

codecov: true
coveralls: true

after_success:
  - julia -E 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
